language: python
sudo: false
os:
  - linux
python:
  - "3.4"
  - "3.5"
  # - "3.6"
  # - "nightly"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install .
script:
  # * E501 - line length limit
  # * E123 - indentation on data structures
  - flake8 . --ignore=F403,E501,E123,E128 --exclude=docs,build
  - nosetests --with-coverage --cover-package=mesa
after_success:
  - coveralls
